name = "drasty-backend"
main = "src/index.js"
compatibility_date = "2026-06-18"

[[d1_databases]]
binding = "DB"
database_name = "drasty"
database_id = "5e611c8e-c0b3-49f3-b7c3-fbfa2632b9e0"

[ai]
binding = "AI"
